##########################################
# Fantôme NCAT patient 1
#########################################

/gate/world/daughters/name phantom
# Use a voxelized navigator
/gate/world/daughters/insert ImageNestedParametrisedVolume #ImageRegularParametrisedVolume
/gate/phantom/geometry/setRangeToMaterialFile /homes/ymellak/PR_Correction/GateSimulations/AttenuationRangefinal.dat
/gate/phantom/geometry/setImage /homes/ymellak/PR_Correction/NewData/Phantoms_Ga68_{resolution}mm/Phantom_{number}/image_{number}.h33
/gate/phantom/placement/setTranslation  0. 0. 0. mm
/gate/phantom/attachPhantomSD
#/gate/phantom/setSkipEqualMaterials 1

